---
title: "Advice for the academic job market"
---

Last updated: 31 October 2022.

For many years I kept a PDF file of these thoughts, originally
drafted as I was going through the market for the first time 
in 2012. Now, ten years later, much has changed. And many others have written similar documents (see especially [Irina Gaynanova's](https://irinagain.github.io/Resources/AcademicJobMarketAdviceIrina_v2.pdf) excellent advice). Nonetheless,
I often hear from junior scholars that they found these useful, so I've converted them to markdown and posted it here.

# What to expect

First of all, the market is strange but can be exciting. If you have very few constraints, you may end up sending out 40 / 50 / 60 applications. Send as many as you can stomach. You will likely never hear from 75% again. Don’t worry, you’ll get a job. Some of these will want phone interviews, others will just invite you out for the interview. Try not to equate contact / interviews / offers with your own self-worth. Most places have specific things in mind which are not indicated on the posting. They know immediately that you are not a good fit. Lower end departments may not contact you because they think that you would never accept their offer. In my year, many places receive 200+ applications. 

Unfortunately, there is lots of randomness involved. You need to be in the top 5-10% of applications to get noticed. And every year, there a handful of amazing candidates who will interview everywhere (in 4 trips through the market, this has never been, nor I suspect will ever be, me). If 50% of applications are plausible, and in most searches I've been on, this is the case, (under some standard assumptions) you will need 20 applications to give yourself an 85% chance of landing 1 interview. It's unfortunate that this is the case, but also means you may well get interviews at places you never expected.

Don’t apply to places you absolutely won’t go. You’re just wasting your own time. Do apply to any place you think you might go. And apply anywhere you think there is someone you want to talk to. Remember, this is a chance to freely get your name out and talk to senior faculty that you may never have the opportunity to see. Even if you don’t like the school, you can still make contacts on their dime.

You may well get phone interviews immediately in November / December and then nothing until late January or early February. Don’t worry, some places are slow.

Overall, try not to stress too much. You may not hear from that one place you really wanted to go, but there will be opportunities, and sometimes places you didn’t really think much of will turn out to be really great.

Once you start getting calls, you can have your advisor contact someone from that place you really want to go. Don’t do it yourself unless your advisor approves it. This is on them.

# Documents

There are essentially 4-5 important documents, though some places will ask for a few other related things. Try to make them look nice, even using the same formatting for everything. It's just a marginal improvement, but it immediately says that you are organized and care about what you are doing.

* Don't use Microsoft Word for things. It almost always looks tacky.

## The CV

* Include your school or a professional email address. If you don't have one, get one.
* Include your cell phone number.
* Link to your website (and create one so we can find you).
* Be sure it's easy to find things. This should be clean. Unless you have a graphic design background, don't try to have novel formatting. It will likely make you stand out in an undesirable way. Many search committee members will do a first pass on your CV only, so the clearer this document, the better. Search for examples from faculty you trust online, and mimic their formatting.

### Papers

Here you should put everything that you have. Divide papers into sections: published, papers under review, papers in progress. Put anything that exists as a document and that you can talk about for 2 minutes in one of these categories. But for it to be here, it should actually be a paper (preferably linked and on [arXiv](https://arxiv.org) or [bioRxiv](https://www.biorxiv.org) or similar). 

And be absolutely certain that you can articulate the main points, contributions, and difficulties for every paper you list.

You can get an interview with a few publications. You may not get an interview if you have many publications. If you have no publications, it is very unlikely that you will be competitive. That's just the current market unfortunately. But, having been on many search committees, I can truthfully say that a 1-2 good publications combined with strong letters can go a long way when everything else is really solid.

## Teaching statement

Really, this is about teaching philosophy. In all likelihood, you have not taught. So talk about how important teaching is, how much you care about students, what makes a good teacher, etc. If you have taught, back these up with concrete examples. It is also good to talk about professors you had (and liked), and the things that they did that you would implement in your own teaching. Don’t say anything negative about anyone. 

Many faculty may not read this. It doesn’t matter. Make it good anyway.

Don't talk about how "education can change the world" or "I've wanted to teach since I was 6". I do read these, and that sort of puffery is always off-putting. You're going to teach, and I want to know that you're committed to doing a good job, and that you have good models for how to do it. Be concrete and genuine.

Probably 1-2 pages, no more.

The first and last paragraphs should summarize the intervening paragraphs. 

Make it so someone can stop after the first paragraph and get the gist (including anything really important), because many people will.

## Research statement

Here you should describe all the work you put on your CV. Describe why you care about a project. Maybe divide it up by topic area. 

The first few paragraphs should give an overview of the rest of the document, again so that someone can quit reading at this point and have some idea of what you care about. 

Demonstrating that your work can be tied together into a specific area that you're passionate about is important. Having a clearly defined research agenda is important for us to project your future: how will this person get grants? who will write tenure letters? etc. It also demonstrates that you know the field, and can connect with it.

In each section, include ideas for future work. Put that in italics or bold so that readers immediately see that you intend to have a long and productive research career.

Probably 2-4 pages, no more (or less). My fourth page on the Assistant Professor market was mainly references (with hyperlinks) to the papers I talked about in the text.

## Cover letter

This document is important. I mean it. I always read it.

It needs to be (lightly) customized to every department. Start with "I am applying to the advertised opening for a XXX in XXX". Then say why you want to go to school XXX. Then highlight what your research is, why it is awesome, why you are a good teacher (if it is a teaching position), and why you are a fun person (you like long walks on the beach and swing dancing).[^walks] Remember that we are hiring a colleague. We want to get along with you. 
Mention anything that is cool and personal but maybe not on another document or hard to find on another document.
Say how great you think school XXX is again and how great a fit you will be.
Address it to a person if possible, if not "Members of the Search Committee" is fine. Try to put the address of the department on top.

[^walks]: I'm being facetious here. Don't tell me you like long walks on the beach. But do tell me anything that you think it is important for me to know about you. Highlight the most important things from the rest of your materials, and point out anything else I should know that doesn't have a natural place.

* Use macros as much as possible. That way you can substitute out the name of the position and the school easily without making mistakes. I had to go back to the post office to retrieve an application for Wisconsin when I realized that it said Stanford halfway down the cover letter. (Didn't matter, neither interviewed me.)

## Diversity statement

This is becoming more and more common. In my opinion, it should always be mandatory. It's really hard to give concrete advice on these. In my experience, it's unlikely that this will put you over the top, but doing a poor job can absolutely sink you. 

For me (a straight, cisgender, white man), what I'm really looking for is a recognition that diversity is important. And that you, as a privileged faculty member in the ivory tower, are going to take meaningful action to address it in some way. There are all sorts of ways to describe and motivate the statement. I tend to look for concrete actions more than anything else. If you advocated for another female student who was not being treated fairly by a male professor, this is a place to describe that. Sometimes people use this to describe how they personally are from a diverse background. That can be important to discuss, especially as it speaks to how you would interact with students and colleagues and help to protect others from undergoing treatment that you experienced. 

I have often read grant applications and other documents where applicants (senior people) try to quantify their contributions with statements like "my lab currently has 3 women and 4 students from underprivileged backgrounds". This is NOT diversity, and for me is uncomfortably close to empty statements like "I'm can't be against XXX. I have a friend who's XXX." Avoid making statements like that.

There are many ways to think about this statement. And there are probably lots of resources online. But, if you have some time, it's worth reading Ibram X. Kendi's ["How to Be an Antiracist"](https://www.powells.com/book/how-to-be-an-antiracist-9780525509288). The book is written mainly about race, but the lessons are broadly applicable and important.

## Takeaways

Every member of every search committee views these documents differently. Indiana University would pay for 2–3 flyouts. UBC brings more like 6 candidates. We typically make cuts in a few stages: (1) remove all those not suited (50% reduction); (2) each member ranks the remainder from 1–3; (3) keep all candidates ranked 3 by any member; (4) cut down to 6–10 candidates to give phone interviews.

Sure ways to get cut in stage 1 include having incomplete applications and having a CV produced in Microsoft Word with coloured highlights or otherwise looking non-academic. Unfortunately, the first cut is almost always based entirely on the CV. Getting to stage 4 is the hard part, and often based on some amount of luck. It is also very difficult for us to do. We usually have more than 30 candidates who all look like plausible hires that we would want. At this point, we’re looking for (a) really strong research record; (b) really strong letters of recommendation; (c) evidence of teaching strength; and/or (d) reasons to believe that you want to come here. Any of these can get you to the phone interview, but (c) and (d) are more important than you might expect. Like it or not, you WILL have to teach undergraduates, so if it looks like you’ll be a disaster, you’re out. Trying to infer this is difficult, and often depends more on your listed teaching experience and your letters of recommendation than on your teaching statement. As for (d), we look at where you’re from, if someone has met you, and what you say in your cover letter. This is the place where generic applications hurt.

I just want to emphasize that last point again. Making a strong case in a cover letter why "this place" is for you can really help. We know that the first offer we make is not the only offer that this person will receive. So if you have strong reasons, that can make a difference, especially at the cut-to-interview stage. We'd rather bring candidate 7 who says they really want to come than candidate 6 who had a completely generic application, if everything else is close.

As for the research record, we are looking for evidence that you can do research on your own. This is not the same as a long list of published work. A long list of published work with the same co-author (advisor) all the time makes us nervous. Having one publication in JASA or Annals or JMLR and nothing else listed as in progress similarly makes us nervous. We want to know that you can do work away from your advisor and have things that will be ready to be submitted in the next few years. We often have post-docs who are hard to evaluate because they have 2 good publications with their dissertation advisor and 2 more with their post-doc advisor, but we know that the advisors invented these areas of research. This makes us wonder whether the person can come up with their own topics. This is another place that letters are important.

# Interviews

Be prepared to give a summary of your main research interests. This should usually start with motivation. Think about 3 different versions: the 30 second version, the 2 minute version, and the 5 minute version. All may come in handy. Don’t memorize them, you’ll sound rehearsed unless you are a brilliant actor. These should be natural.

## Zoom / phone interviews

These may or may not occur prior to an in-person interview. They generally last 30 minutes to an hour. You will be on the phone with a few members of the search committee. Sometimes they will have a standard list of questions to ask you. Here are a few samples.

* Why did you apply to our university?
* Are there any faculty whose research particularly interests you?
* What are some of the courses listed on our website you might want to teach?
* What is your philosophy about research? Do you like theory? Applications? Combination? 
* What is the motivation for your thesis research?

Sometimes the questions will reference your website or other information that is available about you online or in your collection of documents. 

There will generally be time at the end for you to ask questions. It is very important that you ask some. Ask things that show that you have thought about the university and want to go visit. Some samples.

* How many courses will I be asked to teach and what types? 
* Where do you see the department going in the future?
* When will I hear about being invited for an interview?
* I saw that XXX is interested in XXX, blah blah blah?

I personally find these incredibly helpful. There is almost always a top candidate who bombs out, while another takes a big leap. We are looking to see what you know about the department and to discern whether you want to be here and if you can speak in front of people. We always have a prepared list of questions. Last year, we started by asking a question about the advertisement we posted. We always ask what kinds of classes you want to teach. Don’t answer "anything". It’s much better if you can say, "I looked at your website, and I’m really interested in teaching X and Y." In our case, new hires typically teach a graduate-level course in an area of their choosing as well as one of the standard undergrad courses. It’s better if you say "I want to teach your S3XX course" than "I want to teach RKHS to the undergraduates." 

Before the phone call, read over everything that you can about the department. The website, each faculty member’s research area, the official ad, information about the city, etc. This is good advice for any interview (university or private-sector).

## Flyouts

Interviews are fun but long. A standard flyout begins at 9am and lasts until 4 or 5pm with a 50 minute talk somewhere in the middle. Usually there is dinner either the night before, the night of, or both. That said, it is not nearly as stressful as it would seem. People just want to get to know you. It is as much about them convincing you to go there as it is about you convincing them you’re hot stuff.

From the moment something is scheduled for you, be on your best behavior. Be nice to the driver from the airport, the people at the front desk of the hotel, and the department secretaries. Any or none of these people could potentially have some small input into a hiring decision. By the same token, don’t dress like a slob at any point (even on the plane). Wear clothing you would be comfortable in if you wanted to impress someone. Nice jeans and a nice shirt is fine. In fact, this same outfit may be fine for the actual interview.

In general, statistics departments are not very formal. Business casual is usually fine. This means slacks and a button down shirt for men or women, perhaps a skirt, a vest or sweater over top, etc. You may even be able to wear nice, dark coloured jeans without rips or worn marks. Sometimes a tie is nice, but not really necessary. Think of what a well dressed professor in your department might wear. For business schools or industry, wear a suit unless told otherwise. That said, shave, cut your hair, try to look like someone who tried instead of someone who has given up on life. Make sure your clothes fit, etc.

There may be some walking involved, and interviews often take place in the winter. Bring things to be comfortable with the temperature and weather.

There are a few items that you should make sure to have. Use a backpack. Unless you go to a business school or a finance company, then get a briefcase.

* Pen and paper
* List of questions to ask
* Laptop with your talk, and whatever is necessary to make it project
* USB key with your talk on it. Or put it online. Or both. You may need to use a machine that's not yours.
* A bottle of water (you are going to talk for the next 8-10 hours and your mouth will get very dry)
* Chapstick and other personal hygiene items you don’t want to be without
* $20 cash in smallish bills. You may need to tip a driver or a bellhop or something.

You will generally meet with a bunch of people for 30 minutes to 1 hour each. You will likely meet a Dean and the Department head. The Dean may know nothing about you. He/she may need the 30 second version of your research.

This time, be prepared to ask lots of questions. You can (and should) repeat these to everyone you meet. It hurts nothing to ask 3 people the same question. Ask anything that is important to you. If you like playing sports, ask about sports. Whatever. Some of these are probably better suited to asking your dinner / lunch host(s). If you have a two-body problem, avoid questions relating to your significant other unless this information is already open (see below). These are better handled during the negotiation, once they offer you the job, or perhaps in your meeting with the Head. They (legally) cannot ask about such things unless you bring it up. Don’t ask what the salary is. This is a bit more delicate, and you want to know, but this is actually somewhat standard. More below.

* For anyone
    * What do you like about the department?
    * What do you dislike about the department?
    * How is the department socially?
    * How are the students?
    * How are the graduate students supported?
    * What is the expectation about grants?
    * Tenure?
    * Where are the good places to live? (This shows you want to come here) 
    * How are the public schools? (again)
    * Do you get graders/TAs?
* For the department head
    * What is the startup package?
    * Will I get summer support?
    * Computing support?
    * Travel support? (These last three are the usual startup package)
    * How do Stats Journals vs Discipline journals play in the tenure decision? 
    * How does teaching/research/service balance in the tenure decision?
    * Are there intermediate reviews?
    * Teaching releases?
    * How much service will I do in the first few years?
* For the Dean
    * Cost of living
    * How does the department fit in the school? The university?
    * University/School level funding opportunities?

Again, they want to get to know you. It is doubtful that you will get tricky research questions at any point (even really during your talk). It’s not a quiz. Just relax and have fun. Use all the time you have. There were interviews where I filled the whole time with my own questions and they asked me nothing. This is probably not ideal, but sometimes you get someone who really likes to talk.

Talking about spousal issues is tricky. In some cases, you actually want to mention it to the Head now (you may even want to do it when you're offered the fly-out). Some universities are good at making spousal accommodations and, the more time they have to do it, the more likely it is that they can find something that your spouse will like. This may not be the case at all places though. Getting an offer usually comes with a 2–week timeline. Waiting until the offer to try to get a spousal hire then means sending in an entire application and hoping another department can review it and bring out the person in a very short amount of time. If we know when you fly out (or when we offer you the fly out), we can start the process immediately. That said, other places may not be as pro-active as we are. 

My personal view is, if they discriminate against you for a spouse or kids, you don’t want to be there. It is (in my opinion) very unlikely for family issues to lead to a candidate not getting an offer. But some places may not be willing to get your partner the type of position they want. This is something you should think about carefully as soon as you get an offer for an interview. Ask your advisor or others if they know the department / university. Have a plan with your significant other for how to handle this situation. Talk about this early, probably when you're sending out applications.

# The talk

The talk is serious. Spend a lot of time making the slides, and make them good. 

I used Beamer for many years, but now I tend to use [`xaringan`](https://slides.yihui.org/xaringan/#1) with a number of modifications.[^xaringan] If you use Beamer or anything else, do something about the defaults. Just make it look different. Change the colours, use a non-standard theme, something. Standard blue is boring. Create a colour scheme with colours that don’t clash. And be cognizant of colour blindness. This is more common than you think.

[^xaringan]: This took a long time and iteration to create. And it's not important to get this complicated. In fact, you probably shouldn't. But do _something_ different.

* Most talks are 50 minutes. Shoot for 45 not 55.
* The first 30 minutes should be understandable by everyone in the audience even if they work in survey sampling and you work in inference in an RKHS.
* Don’t use acronyms (like RKHS) until you define them. MLE is fine. So is OLS. Everything else gets defined verbally or on a slide (or both).
* Define non-acronyms as well. Most of the audience is not well acquainted with your area. Plus, the talk should be rigorous. Use good notation and say what things mean. Don’t just assume that everyone understands your jargon.
* Don’t put any proofs in the talk. No one cares. State your theorem, hint at how you might prove it, then spend your time saying why it’s cool and how to use it. Have a backup slide with a proof sketch in case someone asks. You might say what the major difficulty in the proof was.[^cello]
* Don’t say "I’m not going to talk about BLAH". Say "I would be happy to give more details later on if you’d like."
* Don’t stare at your slides. Look at the audience. All of them. Especially the guy looking right at you.
* Don’t fiddle with your collar or the water bottle or whatever else is at hand.
* Don’t waggle the laser pointer at every single word on every slide. Use it VERY sparingly if at all. Your slides should be minimalist enough that the important bits are obvious. Heck, highlight them in pretty colours using those macros.
* Get a bottle of water before the talk. This is my trick for going slowly, staying hydrated, and emphasizing important points. Pick a few key slides that are maybe a bit complicated. After you talk about them, slowly remove the bottle cap and take a drink. This will help you relax. It will also give the audience a few seconds to get the hard stuff into their head.
* Don't read your slides. 
* Explain your graphics. All parts of it. Especially the axes and the colours.
* Don't put tables on slides unless they have < 5 numbers. And probably not even then.
* Make sure your talk has a nice structure. Use verbal transitions in between portions of your outline: “Now that I’ve told you about Section B, we’re ready to move on to Section C.” This helps people stay engaged and know where you’re going. Repeating the outline slide is probably no good. People never know what to say on those things, so they just flash by and look useless.
* *BE EXCITED*. You’ve worked hard on this. All results are cool. Play them up. You did something good and you want to tell everyone about how awesome you are. Own it. If you proved a theorem, say “I showed this” not "It can be shown".
* Include future work. This says that you have an idea of how you’re going to spend the next few years.
* Reference related papers you wrote, published or not (if not, put it on arXiv). This goes along with demonstrating how great you are.
* If you’re talking about only part of your thesis or research agenda, say how this part fits in with the rest. Reference the other papers you wrote.
* Plan to spend the first five minutes (or maybe more) doing motivation. If this is an applied talk, introduce the application thoroughly and explain why it’s interesting in general and also why it’s interesting to you. If your talk is more theoretical, motivate the theory with an intended application. Explain the real world problem you are interested in solving and how this led you to the particular theory. We are statisticians, and most departments like some application. And there will be people in the audience who do nothing but applied work. You need to appeal to them too.
* Don’t display the total number of slides as in 6 / 85 in the lower right hand corner. But do include slide numbers so that someone who wants to ask a question can easily direct you to the appropriate slide.
* Have lots of backup slides. Nothing looks better than when you anticipate a question from the audience and have a slide that answers that question.
* Do a practice talk. Do multiple practice talks. Invite friends, your advisor, and someone that doesn’t know your stuff. This will help you make sure that you can handle a broad audience. Any questions should precipitate backup slides. The last job talk I did (after having been a professor for 8 years and giving lots of talks), my wife and her colleague (neither in any field anywhere close to statistics) listened to my practice talk and had many useful suggestions. Talk to anyone.
* This is a sales pitch. I cannot emphasize enough that this is your best chance to be charismatic and show people how great you and your research are. And the better you teach it, the better the audience will think you will be in a class with 100 undergraduates.

[^cello]: When I performed music regularly, there would be passages that was very challenging. You had to practice them until they were really easy. Then keep practicing until you could play it with ease, while making it seem hard. Theorems are like this. They should be immediately intelligible to the audience, but seem like they took a lot of work to prove. But don't show the proof.

I cannot reiterate enough how important the talk is. We have looked at your papers already. And we know that you know this material backward and forward. If the talk is hard to understand, you’re done. How can we count on you to teach undergrads if you can’t explain the stuff you understand best to statisticians? 

Be very wary of putting lots of equations on your slides. At the same time, a talk in CS style which has lots of pictures but no equations and is more high-level will not generally be well received in Statistics. We want to really understand the methodology, so simply saying "we use mincut on the image" is not enough. Prepare yourself to describe things very carefully. 

Define notation. *BE ORGANIZED*. We see too many talks (including invited talks by senior people) that are terribly disorganized. Plan your transitions. Motivate your methodology.

In my own trips to give talks, I have found that certain departments do things differently. Our department tends to saves hard questions for the end, unless we’re just confused. But some departments start asking questions (and lots of them) on slide 1.[^econ] It helps to know this beforehand. Now when I give talks, I ask whoever invited me what the format is. If it is a place where I can anticipate lots of questions, I need a plan for how I can still make my point without using all the slides. It’s bad if I have to look at each slide for 10 seconds before deciding I need to skip it for the sake of time.

[^econ]: Economics and finance departments almost always do this.

# Negotiation

Alright, you got an offer. Congratulations! Now what? Don’t accept it. You deserve more money than they offered you. They made you the offer because they want you there. Make them work for it.

## Salary

Look at the ASA salary survey. The department head making the offer probably has. In 2011 (yes, ages ago, but I haven't checked recently), the median salary for a first year Assistant Professor at a US research university was \$80,000. The median at a teaching university was about \$60,000. This is likely where the offer will be. The goal should be the 3rd quartile which wass about \$5000 more in each case. You’re qualified, and they want you. So you should shoot for that. 

You may not get it. Salary can be either flexible or inflexible. It is often constrained by the person who got the job last year. The department head will have a hard time giving you more money than that person. There are sometimes other considerations as well like taxes. Some places have no income tax, so they pay you less. The 90th percentile is nice, but it’s for New York, San Francisco, Texas, and business schools. If you’re not there, you’re not going to get it. Also, in the US, these are usually 9 month contracts. You should think of your actual salary as 11/9 of the 9 month salary because you can get (usually) 2 months of summer support through grants and startup. The amount of extra will be in your contract. In Canada, it's a 12 month contract, and you cannot pay yourself extra with grant money. Labour laws are different here.



## Startup package

This is generally where there is a lot of freedom to make the offer more competitive. The startup package may have 6 components, all of which are negotiable: (1) teaching releases, (2) summer support, (3) research/travel funding, (4) graduate assistant support, (5) moving expenses, and (6) computing resources.

Teaching releases are potentially difficult to negotiate, but you should be able to get 2–3 classes off prior to tenure depending on the teaching load. Most research universities have 2+1 loads, meaning 2 classes one semester and 1 the other. If the load is less, you will get fewer releases. If it is 2+2, you should get more like 4 releases. To get it: you need this time at the beginning to get settled without teaching too much. You will likely need it in year 3 to apply for grants and prepare for the interim review. Don't underestimate how important teaching leave is. It can make your life much more managable. Teaching _will_ suck up more time than you think.


Summer support is one of the easiest things to ask for, and it is potentially a lot of money. You should get anywhere from 2–4 months of support. If 4, it will be over the first two years. The reasons for summer support are to aid with course prep, to collaborate with people from your previous institutions, to write grants to get future summer support, and to finish up papers left over from grad school.

Research and travel funding is another easy thing to get, because, like summer support, it is a transitory expense. Salary increases cause lots of issues. You should be able to get \$50,000–\$250,000 spread over the first 3 years. This is to buy text books and to go to conferences. It may be to buy computers or software, though basic computing (along with office equipment) is generally separate. You want to go to conferences so that you can say nice things about your university and become a hotshot. This is an advertising budget. 

If it's at the high end, it may also include RA support or post-docs. Sometimes the summer salary is rolled into this. Sometimes you _cannot_ pay yourself out of this budget. Ask. 

Some places may offer you a graduate assistant (or it's part of the money above). This is probably more useful if you do more applied work. You may not get to choose the assistant, and more senior faculty will often claim the best students. In the US, for my first job, I didn’t see this as crucial. On the other hand, I know someone who successfully negotiated for a post doc for 2 years, so if this is something that is important to you, go for it. In Canada, RA support is more important.[^ras]

[^ras]: I can say more. Feel free to ask.

Moving expenses are variable but seem to be at least \$3000 up to around \$7000 unless you are moving pretty far. Many of the places that I have heard of actually have this mandated by the government, so it’s fixed. But it’s still worth asking about.

Most places will give you a "standard" computer and printer, whatever that means. If you need serious computing resources regularly, you can ask for a more serious computer. Most places will have a computer guru and a cluster that you can use. So for most people, this is probably less of an issue. On the other hand, you may want an office computer and a laptop. So you can ask for that. But they may say to buy it with your research / travel money.

The salary is hard to negotiate, and different universities do this differently. In some places, you ask the department head for something and they go to the dean. In others, you negotiate with the head or chair, and in others, with the dean. My experience is that the salary is basically fixed without a counter offer from a similar institution. And often, fixed even then. Sometimes our department tries to hire people who got MUCH stronger offers from other departments, but these departments were often in MUCH more expensive locations. Deans know this and won’t budge. You should spend some time honestly comparing the cost of living. Don’t just accept an offer that’s 25% higher. Likely the COL is 50% more. 

# Some final thoughts

Really think about everything that is being offered. Don't make the decision based only on money. And don't do it only on prestige. You're going to live in this place and work with these people for many years (though people move more often than you think, moving has high costs, and shouldn't be your goal). Teaching less is huge. Better graduate students is huge. Active colleagues who will collaborate with you is huge. A supportive department Head, or kind senior colleagues, can often protect you from burdensome service and advocate for easier course assignments. A generally supportive environment is really helpful for mental health. These things can massively increase your research productivity. And as a new assistant professor, this is going to be a major priority. 

But don't overlook quality of life. Do people go on vacation? Have families? Work all hours of the day and night? Socialize? Seem kind and respectful to each other? It will help you be happy to be in a place where others live the way you want to live.
