---
title: All papers and preprints
---

```{r, warning=FALSE, echo=FALSE, out.width="100%", out.height="2.5in", fig.width=12, fig.height=2.5, message=FALSE}
#| column: screen
source(here::here("assets", "pub-resources", "djm_flow.R"))
pal <- c("#01364f", "#247c86", "#84231e")
color_fun <- convex_comb(pal[1:3], c(.85, .15, 0))
djm_flow(pal, nlines = 1000, geom_type = "geom_point",
         tapering = "bellshaped", noise_types = "perlin", 
         lwd_par = .1, min_length = 20*.01, iterations = 100,
         top = 20 * 1.5, bottom = 20 * -0.5,
         color_fun = function(x, y) sample(pal, length(x), TRUE)) +
  ggplot2::coord_fixed(expand = FALSE)
```


```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(bib2df)
library(dplyr)
df <- bib2df(here::here("assets", "pub-resources", "papers.bib"), separate_names = TRUE)

keep_fields <- toupper(c(
  "category", "author", "booktitle", "edition",
  "editor", "howpublished", "institution", 
  "journal", "pages", "publisher", "number",
  "title", "volume", "year", "arxiv", "url",
  "code", "pdf"))

df <- df[, keep_fields] %>% arrange(desc(YEAR))
source(here::here("assets", "pub-resources", "render-pubs.R"))

df2 <- df %>%
  transmute(
    year = clean_str(YEAR),
    title = fmt_title(TITLE),
    pub = fmt_jvpy(CATEGORY, JOURNAL, BOOKTITLE, VOLUME, PAGES, year),
    links = fmt_links(URL, ARXIV, PDF, CODE),
    skip = is.na(URL) & is.na(ARXIV) & is.na(PDF) & is.na(CODE)
  )
df2$authors = sapply(df$AUTHOR, fmt_names)
df2 <- df2 %>% filter(!skip)
```

```{r, error=FALSE, warning=FALSE, results="asis", echo=FALSE}
#| column: body
for (i in seq_len(nrow(df2))) {
  ref = df2[i,]
  if (ref$skip) next
  cat(ref$title, "\n")
  cat(ref$authors, "\n")
  cat(ref$pub, "\n")
  cat(ref$links, "\n")
}
```
