---
title: "Inviting Professors to Speak at your Event: Best practices"
date: 2020-03-01
categories: 
  - professionalization
  - advice
---

An undergraduate student approached me in Spring 2020 to give a 20-minute talk on Benedict Anderson’s _Imagined Communities_. He described the event and then told me that the talk was to take place… the following week. To his credit, after I explained why that timeline was impossible, the student asked me for advice on how to successfully and respectfully invite speakers for future events. I chatted with a few colleagues about their preferences and came up with the following guidelines.

When possible, include the following in the invitation:
* Date, time, location (with address), duration of entire event
* Title and abstract of event (with link to website / facebook event page when possible)
* Expectations: is it a formal talk? an informal roundtable? an open discussion? How long should the prof's remarks be? 5-10 minutes? 20 minutes?
* How strict is the format/content of the prof’s talk? In other words, are they free to speak about whatever they want or are you looking for a particular topic?
* Will s/he present alone or will other participants be present? 
* Can/should s/he use a PPT, video, audio, etc.?
* What other expectations are there? (In most events, a speaker just speaks and participates in a Q&A, and there is an organizer that facilitates the rest of the event). If you hope that the speaker will prepare something else (discussion questions, conversation facilitation, etc.), explicitly request that. Keep in mind: they may say no! 
* Is there a meal? Reception?
* Will it be recorded? (they may request that their speech is _not_ recorded)
* Availability to meet or respond via email to answer questions, etc.


In the ideal scenario, you give your speaker(s) enough forewarning that you have not yet determined the precise date/time/location. In those instances, you are able to work around your speaker’s schedule.

#### Timing
* Give ample forewarning. For a 10-minute talk, at least one month in advance. For a 20-to-30-minute talk, at least two months, but ideally longer. 
* When events take place in non-business hours (after 5PM), things get tricky because professors have children, live off campus, etc. I conducted an informal survey of my colleagues at UBC and abroad, and they said for an after-hours event, they require a minimum of two months’ notice, because of arranging childcare and scheduling around other commitments and life.
* If the event happens off campus, give more notice (2 months minimum).
* The bottom line is, profs need plenty of warning, because we are busy. We teach classes, mentor graduate and undergraduate students, write books and articles, serve on myriad committees, and have private lives. So, aim for two months of notice to allow the prof to prepare a quality presentation.

Below is an invitation that I received in mid-February for an event in late March. As you’ll note in the first paragraph, the organizer had already informed me about the event (date, topic, length of talk) verbally in January. I have taken out specifics, but the form gives a good idea of what type of information should be provided to a speaker.


> Dear Tamara,
> 
> I know I mentioned this to you some time ago, but I have been remiss in following up. Here is more information about the event to mark X (specific thematic details).
> 
> First, it will take place on DATE & TIME, in the Choi Centre at UBC.
>
> The basic idea is to look back on the past forty years and identify some of the key elements of that history. There will also be contributions from SCHOLAR 1, ACTIVIST 2, POLITICIAN 3, and myself.
> 
> I suggest that each of us speak for 5-10 minutes (no more than 10), and then open up a general discussion with the audience.
> 
> The event will also be accompanied by an exhibition from X.
>
> Do let me know if you have any questions.

