---
title: "Natalia Beristáin, Rosario Castellanos and Violence Against Women"
date: 2020-01-31
categories: 
  - literature
  - reflections
---

At a January 2020 screening of _Los adioses_, I was invited to give a talk on the work of director Natalia Beristáin. The below is a transcript of that talk.

>  _La violencia es microscópica… Y también es macro._

This quotation serves as a sort of through-line in the films of Natalia Beristáin, director of _Los adioses_, whose creative work I will briefly discuss today in relation to the contemporary social and political situation in Mexico. Shortly, I will return to the above quotation.

Beristáin is the director of two feature length films—2017’s _Los adioses_, and 2012’s _No quiero dormir sola_—as well as multiple short films, including _Peces plátano_ and “La evocación.” Her work is highly regarded, having been nominated for and receiving various prestigious awards. 

Like Lucía Carreras, Lila Avilés, and Natalia Almada, Beristáin is in a class of Mexican filmmakers whose work is concerned with contemporary social issues, such as racism, class inequalities, mental illness, and the drug war. Similar to Almada, Beristáin often deploys a reserved aesthetic, employing sustained shots and unsettling framing to provoke tension and create a pensive narrative atmosphere.

Beristáin’s films focalize complicated present-day social concerns. _No quiero dormir sola_ is a measured reflection on aging and dementia, told through the prism of a multigenerational relationship between two women of the Mexico City artistic class. The film subtly exposes violence against the elderly, a lack of understanding and compassion for the frailties of old age, and a failing social system that cannot take care of its aging population—a crisis that has become a global reality.

The short, “La evocación”, is the final part of the anthology film, _La habitación_, which narrates historical moments in Mexico from the time of Porfirio Díaz to the present. Eight episodes depict different stories that unfold across time in the same room. “La evocación” is the only installment of the film directed by a woman, and the part centers on vulnerable populations, such as victims of domestic violence, the homeless, drug addicts, and orphaned children, who find refuge and a support system in the titular room.

As these brief synopses show, Beristáin’s creative work is often socially engaged, and the most salient recurring theme is, without a doubt, violence against women.

>  _La violencia es microscópica… Y también es macro._

These words are stated by an unnamed woman discussing her experience of gendered violence in Mexico City in the 2019 documentary short, [_Nosotras_](https://www.sopitas.com/entretenimiento/exclusiva-corto-nosotras-feminicidios-violencia-genero-diego-luna-natalia-beristain/), which Beristáin directed. In the short film, a dozen women give testimony about domestic violence, gendered micro aggressions, and femicide in Mexico. Femicide is defined as the murder of a woman based on her condition as a woman, “the murders of women and girls founded on a gender power structure" ([Fregoso and Bejarano](https://read.dukeupress.edu/books/book/1432/Terrorizing-WomenFeminicide-in-the-Americas) 5), and Mexico has one of the highest rates of femicide in Latin America. Violence against women has escalated in recent decades due to increased poverty, the flexibilization of labor, and migration, often effects of neoliberal economic policies. This precarious socioeconomic situation in combination with a traditionally patriarchal culture often proves deadly for women in Mexico. 

Which brings me back to _Los adioses_. When I first heard about the film, I thought “No! Don’t soil my feminist hero with a torrid love story.” I still remember the first time I read Castellanos’s “Lección de cocina," which contains the bitter musings of a newly minted housewife who did not realize that marriage meant trading in her books on philosophy for cookbooks. In _Los adioses_, we hear pieces of “The Cooking Lesson” in a voiceover the first time that marital bliss begins to dissolve in the film and Ricardo intrudes on Rosario’s writing. _Los adioses_ is a reminder that being a feminist does not prevent a woman from confronting machismo at home.

>  _La violencia es microscópica… Y también es macro._

To my mind, one of the most productive overlaps between Castellanos’s and Beristáin’s creative work are the ways in which their projects problematize their own privileged social status. Whether this is a conscious effort or an ideological blind spot is debatable, but both women’s work opens up a productive space to consider questions of privilege in the world of representation.

Castellanos’s “The Cooking Lesson,” for instance, presents a complex portrait of an upper-middle class woman who, in one and the same thought wants to shed the domestic role forced upon her while also speaking wistfully of servants who are free to “switch masters” at will. Similarly, Beristáin’s _No quiero dormir sola_ asks the viewer to feel pity for the aging grandmother, whose wealthy son and her past as a successful actress secure her space in a swanky retirement home exclusively for Mexico City’s “artistes.” This is the prism through which Beristáin problematizes an infrastructure that is ill-equipped for a rapidly aging population.

In closing, despite eliding some of Castellano's major commitments--such as her activism for indigenous communities--Beristáin does a credible job of depicting the complexities of Castellanos’s life as evidenced in her publications, private letters, and public lectures. The film makes palpable the difficulty of reconciling a militant feminist ideology with the warring desire to build a life with a partner whose values are decidedly anti-feminist.

### Works referenced & Links of interest
* http://www.luxboxfilms.com/los-adioses-1
* https://revista192.com/natalia-beristain/
* https://www.youtube.com/watch?v=1CmPWcRUaFY
* http://www.elojoquepiensa.cucsh.udg.mx/index.php/elojoquepiensa/article/view/171/175
* https://soundsandcolours.com/reviews/film-reviews/los-adioses-40849/
* https://gatopardo.com/arte-y-cultura/directoras-de-cine-mexicano/
* https://www.revistadelauniversidad.mx/articles/4167e7ff-acee-49cc-888b-349ba2e7f198/por-amor-al-arte
